import type { Metadata } from "next";
import "./globals.css";
import Cursor from "@/components/cursor"
import ClickEffect from "@/components/ClickEffect";


export const metadata: Metadata = {
  title: "River Ranch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Cursor />
        <ClickEffect /> 
        {children}
      </body>
    </html>
  );
}


